/**
 * Photo-backed text posts — the "headline over a photo" style common on LinkedIn:
 *
 *   photo-headline  full-bleed photo, readable overlay, headline with *emphasised* words,
 *                   a subline, the logo
 *   stat-card       big number + label over the photo, and a white panel with an optional
 *                   chat-style UI mock, a headline and a short body
 *
 * The photo is uploaded, generated by Higgsfield from a scene description (pipeline), a
 * brand photo, or — with none — a brand-colour gradient. The theme decides the treatment:
 * dark = darkened photo + white type, light = white panel + ink type, brand = photo tinted
 * in the brand colour. Same fit + contrast guarantees as the other text layouts.
 */
import { existsSync } from "node:fs";
import sharp, { type OverlayOptions } from "sharp";
import type { Aspect } from "./schemas";
import { CANVAS, avatarImage, escapeMarkup, mix, textImage, type Theme } from "./typographic";
import type { PageRender } from "./slides";

export interface PhotoPostInput {
  aspect: Aspect;
  theme: Theme;
  font: string;
  brandName: string;
  logoPath?: string;
  /** Background photo; omitted -> brand-colour gradient. */
  photoPath?: string;
  headline: string;
  subline?: string;
}

export interface StatCardInput extends PhotoPostInput {
  stat: string;
  label: string;
  /** Draw a small chat-style UI mock in the panel (AI / product posts). */
  chatMock?: boolean;
}

/**
 * Headline markup: *word* or *a phrase* is emphasised (bold, accent colour); everything
 * else is escaped. Unmatched asterisks are kept as text.
 */
export function emphasisMarkup(text: string, accent: string): string {
  const parts = text.split(/(\*[^*\n]+\*)/g);
  return parts
    .map((p) =>
      /^\*[^*\n]+\*$/.test(p)
        ? `<span weight="heavy" foreground="${accent}">${escapeMarkup(p.slice(1, -1))}</span>`
        : escapeMarkup(p),
    )
    .join("");
}

const rect = (w: number, h: number, fill: string, r = 0, opacity = 1) =>
  Buffer.from(
    `<svg width="${w}" height="${h}"><rect width="${w}" height="${h}" rx="${r}" ry="${r}" fill="${fill}" fill-opacity="${opacity}"/></svg>`,
  );

/** Vertical/horizontal alpha gradient of one colour (for readable overlays). */
function fade(w: number, h: number, color: string, from: number, to: number, dir: "down" | "up" | "right" | "left") {
  const [x1, y1, x2, y2] = dir === "down" ? [0, 0, 0, 1] : dir === "up" ? [0, 1, 0, 0] : dir === "right" ? [0, 0, 1, 0] : [1, 0, 0, 0];
  return Buffer.from(
    `<svg width="${w}" height="${h}"><defs><linearGradient id="g" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"><stop offset="0" stop-color="${color}" stop-opacity="${from}"/><stop offset="1" stop-color="${color}" stop-opacity="${to}"/></linearGradient></defs><rect width="${w}" height="${h}" fill="url(#g)"/></svg>`,
  );
}

/** Background: the photo cover-cropped, or a soft brand gradient when there is none. */
async function background(input: PhotoPostInput, w: number, h: number): Promise<Buffer> {
  if (input.photoPath && existsSync(input.photoPath)) {
    return sharp(input.photoPath).rotate().resize(w, h, { fit: "cover", position: "attention" }).png().toBuffer();
  }
  const a = input.theme.name === "light" ? "#E9EEF5" : input.theme.background;
  const b = input.theme.name === "light" ? "#FFFFFF" : mix(input.theme.background, input.theme.accent, 0.35);
  return sharp(
    Buffer.from(
      `<svg width="${w}" height="${h}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect width="${w}" height="${h}" fill="url(#g)"/></svg>`,
    ),
  )
    .png()
    .toBuffer();
}

/** Largest size (step 4px) at which the block fits maxH; reports whether it fit at all. */
async function fit(markup: string, font: string, color: string, width: number, maxSize: number, minSize: number, maxH: number, bold = true, spacingK = 0.12) {
  for (let size = maxSize; size >= minSize; size -= 4) {
    const t = await textImage(markup, { font, size, color, width, bold, spacing: Math.round(size * spacingK) });
    if (t.height <= maxH) return { ...t, size, fits: true };
  }
  const t = await textImage(markup, { font, size: minSize, color, width, bold, spacing: Math.round(minSize * spacingK) });
  return { ...t, size: minSize, fits: false };
}

const logoSize = (w: number, h: number) => Math.round(Math.min(w, h) * 0.085);
const hasLogo = (input: PhotoPostInput) => !!input.logoPath && existsSync(input.logoPath);

async function logoLayer(input: PhotoPostInput, w: number, h: number, margin: number, onDark: boolean, side: "right" | "left" = "right"): Promise<OverlayOptions | null> {
  if (!hasLogo(input)) return null;
  const s = logoSize(w, h);
  return { input: await avatarImage(input.logoPath!, s, onDark ? "#FFFFFF" : "#F2F2F2"), left: side === "right" ? w - margin - s : margin, top: margin };
}

/** Full-bleed photo with an emphasised headline and a subline. */
export async function renderPhotoHeadline(input: PhotoPostInput): Promise<PageRender> {
  const { w, h } = CANVAS[input.aspect];
  const { theme, font } = input;
  const wide = w > h;
  const unit = Math.min(w, h);
  const margin = Math.round(unit * 0.075);
  const layers: OverlayOptions[] = [];
  let fits = true;

  if (theme.name === "light") {
    // White panel carrying the words; the photo stays visible beside / above it.
    const panelW = wide ? Math.round(w * 0.46) : w - margin * 2;
    const panelH = wide ? h - margin * 2 : Math.round(h * 0.5);
    const left = wide ? w - margin - panelW : margin;
    const top = wide ? margin : h - margin - panelH;
    const pad = Math.round(unit * 0.05);
    const r = Math.round(unit * 0.03);
    layers.push({ input: await sharp(rect(panelW, panelH, "#000000", r, 0.35)).blur(14).toBuffer(), left: left + 4, top: top + 10 });
    layers.push({ input: rect(panelW, panelH, "#FFFFFF", r), left, top });
    const sub = input.subline
      ? await fit(escapeMarkup(input.subline), font, theme.muted, panelW - pad * 2, Math.round(unit * 0.04), 20, Math.round(panelH * 0.3), false, 0.2)
      : null;
    const gap = Math.round(unit * 0.03);
    const head = await fit(
      emphasisMarkup(input.headline, theme.accent),
      font, theme.text, panelW - pad * 2, Math.round(unit * 0.085), 28,
      panelH - pad * 2 - (sub ? sub.height + gap : 0) - Math.round(unit * 0.02),
    );
    fits = head.fits && (sub?.fits ?? true);
    const barH = Math.max(6, Math.round(unit * 0.008));
    layers.push({ input: rect(Math.round(unit * 0.08), barH, theme.accent, barH / 2), left: left + pad, top: top + pad });
    const headTop = top + pad + barH + Math.round(unit * 0.03);
    layers.push({ input: head.data, left: left + pad, top: headTop });
    if (sub) layers.push({ input: sub.data, left: left + pad, top: Math.min(headTop + head.height + gap, top + panelH - pad - sub.height) });
    // The panel takes the right (wide) or bottom (tall) side; the logo sits on the photo.
    const logo = await logoLayer(input, w, h, margin, false, wide ? "left" : "right");
    if (logo) layers.push(logo);
  } else {
    // dark: darken for white type; brand: tint with the brand colour.
    const tint = theme.name === "brand" ? theme.background : "#000000";
    layers.push({ input: rect(w, h, tint, 0, theme.name === "brand" ? 0.62 : 0.3) });
    layers.push({ input: fade(w, Math.round(h * 0.65), tint, 0.75, 0, "down"), left: 0, top: 0 });
    layers.push({ input: fade(w, Math.round(h * 0.45), tint, 0.85, 0, "up"), left: 0, top: h - Math.round(h * 0.45) });
    // Keep the headline clear of the corner logo.
    const logoRoom = hasLogo(input) ? logoSize(w, h) + Math.round(margin * 0.6) : 0;
    const textW = wide ? Math.min(Math.round(w * 0.72), w - margin * 2 - logoRoom) : w - margin * 2 - logoRoom;
    const sub = input.subline
      ? await fit(escapeMarkup(input.subline), font, mix(theme.text, tint, 0.08), textW * (wide ? 0.85 : 1), Math.round(unit * 0.042), 20, Math.round(h * 0.2), false, 0.2)
      : null;
    const headMax = h - margin * 2 - (sub ? sub.height + Math.round(unit * 0.08) : 0) - Math.round(unit * 0.05);
    const head = await fit(emphasisMarkup(input.headline, theme.accent), font, theme.text, textW, Math.round(unit * 0.1), 28, Math.min(headMax, Math.round(h * 0.62)));
    fits = head.fits && (sub?.fits ?? true);
    layers.push({ input: head.data, left: margin, top: margin });
    if (sub) layers.push({ input: sub.data, left: margin, top: h - margin - sub.height });
    const logo = await logoLayer(input, w, h, margin, true);
    if (logo) layers.push(logo);
  }

  const image = await sharp(await background(input, w, h)).composite(layers).png().toBuffer();
  return { image, width: w, height: h, fits, note: fits ? "fits" : "clipped" };
}

/** Big stat over the photo + a white panel (optional chat mock, headline, body). */
export async function renderStatCard(input: StatCardInput): Promise<PageRender> {
  const { w, h } = CANVAS[input.aspect];
  const { theme, font } = input;
  const wide = w > h;
  const unit = Math.min(w, h);
  const margin = Math.round(unit * 0.065);
  const layers: OverlayOptions[] = [];

  // The stat sits on the photo: keep it readable with a soft fade behind it.
  const onDark = theme.name !== "light";
  const statInk = onDark ? "#FFFFFF" : theme.text;
  const tint = theme.name === "brand" ? theme.background : onDark ? "#000000" : "#FFFFFF";
  layers.push({ input: rect(w, h, tint, 0, theme.name === "brand" ? 0.5 : onDark ? 0.22 : 0.15) });
  layers.push({ input: fade(w, Math.round(h * 0.55), tint, onDark ? 0.8 : 0.9, 0, "down"), left: 0, top: 0 });

  const statW = wide ? Math.round(w * 0.46) : w - margin * 2;
  const stat = await fit(escapeMarkup(input.stat), font, statInk, statW, Math.round(unit * 0.26), 40, Math.round(h * (wide ? 0.3 : 0.18)), true, 0);
  const label = await fit(escapeMarkup(input.label.toUpperCase()), font, statInk, statW, Math.round(unit * 0.045), 18, Math.round(h * 0.1), true, 0.1);
  layers.push({ input: stat.data, left: margin, top: margin });
  layers.push({ input: label.data, left: margin, top: margin + stat.height + Math.round(unit * 0.01) });

  // Panel.
  const panelW = wide ? Math.round(w * 0.42) : w - margin * 2;
  const statBottom = margin + stat.height + label.height + Math.round(unit * 0.04);
  const panelTop = wide ? margin : Math.max(statBottom, Math.round(h * 0.34));
  const panelH = h - panelTop - margin;
  const left = wide ? w - margin - panelW : margin;
  const pad = Math.round(unit * 0.045);
  const r = Math.round(unit * 0.03);
  layers.push({ input: await sharp(rect(panelW, panelH, "#000000", r, 0.35)).blur(14).toBuffer(), left: left + 4, top: panelTop + 10 });
  layers.push({ input: rect(panelW, panelH, "#FFFFFF", r), left, top: panelTop });
  let y = panelTop + pad;
  const innerW = panelW - pad * 2;

  if (input.chatMock) {
    // Window dots + three message bubbles (AI / product posts).
    const dot = Math.round(unit * 0.012);
    ["#FF5F57", "#FEBC2E", "#28C840"].forEach((c, i) =>
      layers.push({ input: rect(dot, dot, c, dot / 2), left: Math.round(left + pad + i * dot * 1.8), top: y }),
    );
    y += dot + Math.round(unit * 0.03);
    const bh = Math.round(unit * 0.045);
    const bubbles: [number, string, "r" | "l"][] = [
      [0.62, theme.accent, "r"],
      [0.45, "#E7E9EC", "l"],
      [0.38, theme.accent, "r"],
    ];
    for (const [k, c, side] of bubbles) {
      const bw = Math.round(innerW * k);
      layers.push({ input: rect(bw, bh, c, bh / 2), left: side === "r" ? left + pad + innerW - bw : left + pad, top: y });
      y += bh + Math.round(unit * 0.02);
    }
    if (input.logoPath && existsSync(input.logoPath)) {
      const s = Math.round(unit * 0.09);
      layers.push({ input: await avatarImage(input.logoPath, s, "#FFFFFF"), left: left + pad + innerW - s, top: y - Math.round(bh * 1.4) });
    }
    y += Math.round(unit * 0.02);
  }

  const gap = Math.round(unit * 0.025);
  const space = panelTop + panelH - pad - y;
  const body = input.subline
    ? await fit(escapeMarkup(input.subline), font, "#222222", innerW, Math.round(unit * 0.036), 18, Math.round(space * 0.4), false, 0.2)
    : null;
  const head = await fit(
    emphasisMarkup(input.headline, theme.name === "light" ? theme.accent : mix(theme.accent, "#000000", 0.25)),
    font, "#111111", innerW, Math.round(unit * 0.075), 24, space - (body ? body.height + gap : 0),
  );
  layers.push({ input: head.data, left: left + pad, top: y });
  if (body) layers.push({ input: body.data, left: left + pad, top: y + head.height + gap });

  const image = await sharp(await background(input, w, h)).composite(layers).png().toBuffer();
  const fits = stat.fits && label.fits && head.fits && (body?.fits ?? true);
  return { image, width: w, height: h, fits, note: fits ? "fits" : "clipped" };
}
